In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
countries = pd.read_csv("CountriesSD.csv")
summer = pd.read_csv("SummerSD.csv")
winter = pd.read_csv("WinterSD.csv")

## Kim's Edits below (Analysis on the Role of Gender and its Correlation to Medals Won)

In [5]:
#clean any missing values from each dataset
countries.dropna()

     Unnamed: 0              Country Code  Population  GDP per Capita
0             0          Afghanistan  AFG  32526562.0      594.323081
1             1              Albania  ALB   2889167.0     3945.217582
2             2              Algeria  ALG  39666519.0     4206.031232
5             5               Angola  ANG  25021974.0     4101.472152
6             6  Antigua and Barbuda  ANT     91818.0    13714.731962
..          ...                  ...  ...         ...             ...
194         194              Vanuatu  VAN    264652.0     2805.314644
196         196              Vietnam  VIE  91703800.0     2111.138024
198         198                Yemen  YEM  26832215.0     1406.291651
199         199               Zambia  ZAM  16211767.0     1304.879014
200         200             Zimbabwe  ZIM  15602751.0      924.143819

[176 rows x 5 columns]

In [6]:
summer.dropna()

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
0,0,1896,Athens,Aquatics,Swimming,Alfred Hajos,HUN,Men,100M Freestyle,Gold,Hungary
1,1,1896,Athens,Aquatics,Swimming,Otto Herschmann,AUT,Men,100M Freestyle,Silver,Austria
2,2,1896,Athens,Aquatics,Swimming,Dimitrios Drivas,GRE,Men,100M Freestyle For Sailors,Bronze,Greece
3,3,1896,Athens,Aquatics,Swimming,Ioannis Malokinis,GRE,Men,100M Freestyle For Sailors,Gold,Greece
4,4,1896,Athens,Aquatics,Swimming,Spiridon Chasapis,GRE,Men,100M Freestyle For Sailors,Silver,Greece
...,...,...,...,...,...,...,...,...,...,...,...
31160,31160,2012,London,Wrestling,Wrestling Freestyle,Damian Janikowski,POL,Men,Wg 84 KG,Bronze,Poland
31161,31161,2012,London,Wrestling,Wrestling Freestyle,Ghasem Gholamreza Rezaei,IRI,Men,Wg 96 KG,Gold,Iran
31162,31162,2012,London,Wrestling,Wrestling Freestyle,Rustam Totrov,RUS,Men,Wg 96 KG,Silver,Russia
31163,31163,2012,London,Wrestling,Wrestling Freestyle,Artur Aleksanyan,ARM,Men,Wg 96 KG,Bronze,Armenia
31164,31164,2012,London,Wrestling,Wrestling Freestyle,Jimmy Lidberg,SWE,Men,Wg 96 KG,Bronze,Sweden

In [7]:
winter.dropna()

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze
1,1,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, C.",FRA,Men,Military Patrol,Bronze
2,2,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, Maurice",FRA,Men,Military Patrol,Bronze
3,3,1924,Chamonix,Biathlon,Biathlon,"VANDELLE, André",FRA,Men,Military Patrol,Bronze
4,4,1924,Chamonix,Biathlon,Biathlon,"AUFDENBLATTEN, Adolf",SUI,Men,Military Patrol,Gold
...,...,...,...,...,...,...,...,...,...,...
5765,5765,2014,Sochi,Skiing,Snowboard,"JONES, Jenny",GBR,Women,Slopestyle,Bronze
5766,5766,2014,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",USA,Women,Slopestyle,Gold
5767,5767,2014,Sochi,Skiing,Snowboard,"MALTAIS, Dominique",CAN,Women,Snowboard Cross,Silver
5768,5768,2014,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",CZE,Women,Snowboard Cross,Gold
5769,5769,2014,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",FRA,Women,Snowboard Cross,Bronze

In [8]:
summer.sort_values(by='Year', ascending=False)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
31164,31164,2012,London,Wrestling,Wrestling Freestyle,Jimmy Lidberg,SWE,Men,Wg 96 KG,Bronze,Sweden
29885,29885,2012,London,Boxing,Boxing,John Joe Nevin,IRL,Men,56KG,Silver,Ireland
29857,29857,2012,London,Basketball,Basketball,Abby Bishop,AUS,Women,Basketball,Bronze,Australia
29858,29858,2012,London,Basketball,Basketball,Elizabeth Cambage,AUS,Women,Basketball,Bronze,Australia
29859,29859,2012,London,Basketball,Basketball,Kristi Harrower,AUS,Women,Basketball,Bronze,Australia
...,...,...,...,...,...,...,...,...,...,...,...
101,101,1896,Athens,Gymnastics,Artistic G.,Gustav Felix Flatow,GER,Men,"Team, Parallel Bars",Gold,Germany
100,100,1896,Athens,Gymnastics,Artistic G.,Alfred Flatow,GER,Men,"Team, Parallel Bars",Gold,Germany
99,99,1896,Athens,Gymnastics,Artistic G.,Konrad Böcker,GER,Men,"Team, Parallel Bars",Gold,Germany
98,98,1896,Athens,Gymnastics,Artistic G.,Ioannis Mitropoulos,GRE,Men,"Team, Parallel Bars",Bronze,Greece
0,0,1896,Athens,Aquatics,Swimming,Alfred Hajos,HUN,Men,100M Freestyle,Gold,Hungary

In [9]:
winter.sort_values(by='Year', ascending=False)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
5769,5769,2014,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",FRA,Women,Snowboard Cross,Bronze
5358,5358,2014,Sochi,Ice Hockey,Ice Hockey,"IRWIN, Haley",CAN,Women,Ice Hockey,Gold
5365,5365,2014,Sochi,Ice Hockey,Ice Hockey,"OUELLETTE, Caroline",CAN,Women,Ice Hockey,Gold
5364,5364,2014,Sochi,Ice Hockey,Ice Hockey,"MIKKELSON, Meaghan",CAN,Women,Ice Hockey,Gold
5363,5363,2014,Sochi,Ice Hockey,Ice Hockey,"LAROCQUE, Jocelyne",CAN,Women,Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...
84,84,1924,Chamonix,Skating,Figure skating,"BRUNET, Andrée",FRA,Women,Pairs,Bronze
85,85,1924,Chamonix,Skating,Figure skating,"BRUNET, Pierre",FRA,Men,Pairs,Bronze
86,86,1924,Chamonix,Skating,Figure skating,"BERGER, Alfred",AUT,Men,Pairs,Gold
87,87,1924,Chamonix,Skating,Figure skating,"ENGELMANN, Helene",AUT,Women,Pairs,Gold
0,0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze

### Summer Games analysis below

In [10]:
# for each Summer and Winter games now lets split the data up between men and women and then sort in descending order to get the most recent games for each. 
summer_male_olympians = summer[summer['Gender'] == 'Men']
summer_female_olympians = summer[summer['Gender'] == 'Women']

summer_male_olympians.sort_values(by='Year', ascending=False).head(1000)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
31164,31164,2012,London,Wrestling,Wrestling Freestyle,Jimmy Lidberg,SWE,Men,Wg 96 KG,Bronze,Sweden
29761,29761,2012,London,Athletics,Athletics,David Storl,GER,Men,Shot Put,Silver,Germany
29921,29921,2012,London,Canoe,Canoe Slalom,Sideris Tasiadis,GER,Men,C-1 (Single),Silver,Germany
29920,29920,2012,London,Canoe,Canoe Slalom,Tony Estanguet,FRA,Men,C-1 (Single),Gold,France
29919,29919,2012,London,Boxing,Boxing,Tervel Pulev,BUL,Men,81 - 91KG,Bronze,Bulgaria
...,...,...,...,...,...,...,...,...,...,...,...
30500,30500,2012,London,Hockey,Hockey,Marcel Balkestein,NED,Men,Hockey,Silver,Netherlands
30585,30585,2012,London,Judo,Judo,Felipe Kitadai,BRA,Men,- 60 KG,Bronze,Brazil
30527,30527,2012,London,Hockey,Hockey,Edward Ockenden,AUS,Men,Hockey,Bronze,Australia
30608,30608,2012,London,Judo,Judo,Miklos Ungvari,HUN,Men,60 - 66KG,Silver,Hungary
30514,30514,2012,London,Hockey,Hockey,Roderick Weusthof,NED,Men,Hockey,Silver,Netherlands

In [ ]:
summer_female_olympians.sort_values(by='Year', ascending=False).head(15)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Code,Gender,Event,Medal,Country
31124,31124,2012,London,Wrestling,Wrestling Freestyle,Maider Unda,ESP,Women,Wf 72 KG,Bronze,Spain
29841,29841,2012,London,Basketball,Basketball,Candace Parker,USA,Women,Basketball,Gold,United States
29839,29839,2012,London,Basketball,Basketball,Angel Mccoughtry,USA,Women,Basketball,Gold,United States
29838,29838,2012,London,Basketball,Basketball,Asjha Jones,USA,Women,Basketball,Gold,United States
29837,29837,2012,London,Basketball,Basketball,Sylvia Fowles,USA,Women,Basketball,Gold,United States
29836,29836,2012,London,Basketball,Basketball,Tina Charles,USA,Women,Basketball,Gold,United States
29835,29835,2012,London,Basketball,Basketball,Tamika Catchings,USA,Women,Basketball,Gold,United States
29834,29834,2012,London,Basketball,Basketball,Swin Cash,USA,Women,Basketball,Gold,United States
29833,29833,2012,London,Basketball,Basketball,Sue Bird,USA,Women,Basketball,Gold,United States
29832,29832,2012,London,Basketball,Basketball,Seimone Augustus,USA,Women,Basketball,Gold,United States
29795,29795,2012,London,Badminton,Badminton,Saina Nehwal,IND,Women,Singles,Bronze,India
29794,29794,2012,London,Badminton,Badminton,Yihan Wang,CHN,Women,Singles,Silver,China
29793,29793,2012,London,Badminton,Badminton,Xuerui Li,CHN,Women,Singles,Gold,China
29789,29789,2012,London,Badminton,Badminton,Christinna Pedersen,DEN,Women,Doubles,Bronze,Denmark
29786,29786,2012,London,Badminton,Badminton,Jin Ma,CHN,Women,Doubles,Silver,China

In [ ]:
summer_female_olympians.sort_values(by='Year', ascending=False).head(15)

#This will help us see how many female atheletes there are in each discipline for the summer olympics
summer_female_olympians.groupby('Discipline').size()

#nthis will help us see  which ones have medals won 
summer_female_olympians.groupby('Medal').size()

#this will now let us combine the two above so the number of female metals per each disicipline for the summer olympics
summer_female_olympians.groupby(['Discipline', 'Medal']).size()

Discipline           Medal
Archery              Bronze     35
                     Gold       39
                     Silver     37
Artistic G.          Bronze    216
                     Gold      216
                              ...
Wrestling Free.      Gold        8
                     Silver      8
Wrestling Freestyle  Bronze      8
                     Gold        4
                     Silver      4
Length: 156, dtype: int64

In [ ]:
summer_female_olympians.groupby(['Discipline', 'Medal']).size().head(30)

Discipline        Medal
Archery           Bronze     35
                  Gold       39
                  Silver     37
Artistic G.       Bronze    216
                  Gold      216
                  Silver    211
Athletics         Bronze    381
                  Gold      389
                  Silver    393
BMX               Bronze      1
                  Gold        1
                  Silver      1
Badminton         Bronze     26
                  Gold       23
                  Silver     23
Basketball        Bronze    119
                  Gold      120
                  Silver    120
Beach Volleyball  Bronze      2
                  Gold        2
                  Silver      2
Beach volley.     Bronze      8
                  Gold        8
                  Silver      8
Boxing            Bronze      6
                  Gold        3
                  Silver      3
Canoe / Kayak F   Bronze     70
                  Gold       70
                  Silver     70
dtype: int64

In [ ]:
summer_male_olympians.sort_values(by='Year', ascending=False).head(15)

#This will help us see how many male atheletes there are in each discipline for the summer olympics
summer_male_olympians.groupby('Discipline').size()

#nthis will help us see  which ones have medals won 
summer_male_olympians.groupby('Medal').size()

#this will now let us combine the two above so the number of male metals per each disicipline for the summer olympics
summer_male_olympians.groupby(['Discipline', 'Medal']).size()

Discipline           Medal
Archery              Bronze     55
                     Gold       87
                     Silver     76
Artistic G.          Bronze    447
                     Gold      536
                              ...
Wrestling Freestyle  Gold       14
                     Silver     14
Wrestling Gre-R      Bronze    187
                     Gold      180
                     Silver    182
Length: 181, dtype: int64

In [ ]:
summer_male_olympians.groupby(['Discipline', 'Medal']).size().head(30)

Discipline        Medal
Archery           Bronze     55
                  Gold       87
                  Silver     76
Artistic G.       Bronze    447
                  Gold      536
                  Silver    477
Athletics         Bronze    818
                  Gold      826
                  Silver    831
BMX               Bronze      1
                  Gold        1
                  Silver      1
Badminton         Bronze     26
                  Gold       23
                  Silver     23
Baseball          Bronze    112
                  Gold      111
                  Silver    112
Basketball        Bronze    215
                  Gold      222
                  Silver    216
Basque Pelota     Gold        2
                  Silver      2
Beach Volleyball  Bronze      2
                  Gold        2
                  Silver      2
Beach volley.     Bronze      8
                  Gold        8
                  Silver      8
Boxing            Bronze    410
dtype: int64

### Winter Games analysis below

In [ ]:
#now to split it up into the winter olympics and do the same thing as above

winter_male_olympians = winter[winter['Gender'] == 'Men']

winter_female_olympians = winter[winter['Gender'] == 'Women']

winter_male_olympians.sort_values(by='Year', ascending=False).head(15)

,Unnamed: 0,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
5754,5754,2014,Sochi,Skiing,Snowboard,"DEIBOLD, Alex",USA,Men,Snowboard Cross,Bronze
5327,5327,2014,Sochi,Ice Hockey,Ice Hockey,"VATANEN, Sami",FIN,Men,Ice Hockey,Bronze
5319,5319,2014,Sochi,Ice Hockey,Ice Hockey,"PIHLSTROM, Antti",FIN,Men,Ice Hockey,Bronze
5320,5320,2014,Sochi,Ice Hockey,Ice Hockey,"RASK, Tuukka",FIN,Men,Ice Hockey,Bronze
5321,5321,2014,Sochi,Ice Hockey,Ice Hockey,"RUUTU, Tuomo",FIN,Men,Ice Hockey,Bronze
5322,5322,2014,Sochi,Ice Hockey,Ice Hockey,"SALMINEN, Sakari",FIN,Men,Ice Hockey,Bronze
5323,5323,2014,Sochi,Ice Hockey,Ice Hockey,"SALO, Sami",FIN,Men,Ice Hockey,Bronze
5324,5324,2014,Sochi,Ice Hockey,Ice Hockey,"SELANNE, Teemu",FIN,Men,Ice Hockey,Bronze
5325,5325,2014,Sochi,Ice Hockey,Ice Hockey,"TIMONEN, Kimmo",FIN,Men,Ice Hockey,Bronze
5326,5326,2014,Sochi,Ice Hockey,Ice Hockey,"VAANANEN, Ossi",FIN,Men,Ice Hockey,Bronze
5328,5328,2014,Sochi,Ice Hockey,Ice Hockey,"ALFREDSSON, Daniel",SWE,Men,Ice Hockey,Silver
5338,5338,2014,Sochi,Ice Hockey,Ice Hockey,"HAGELIN, Carl",SWE,Men,Ice Hockey,Silver
5329,5329,2014,Sochi,Ice Hockey,Ice Hockey,"BACKSTROM, Nicklas",SWE,Men,Ice Hockey,Silver
5330,5330,2014,Sochi,Ice Hockey,Ice Hockey,"BERGLUND, Patrik",SWE,Men,Ice Hockey,Silver
5331,5331,2014,Sochi,Ice Hockey,Ice Hockey,"EDLER, Alexander",SWE,Men,Ice Hockey,Silver

In [ ]:
winter_female_olympians.sort_values(by='Year', ascending=False).head(15)

#This will help us see how many female atheletes there are in each discipline for the winter olympics
winter_female_olympians.groupby('Discipline').size()

#nthis will help us see  which ones have medals won 
winter_female_olympians.groupby('Medal').size()

#this will now let us combine the two above so the number of female metals per each disicipline for the winter olympics
winter_female_olympians.groupby(['Discipline', 'Medal']).size()

Discipline                 Medal
Alpine Skiing              Bronze     69
                           Gold       72
                           Silver     72
Biathlon                   Bronze     50
                           Gold       50
                           Silver     50
Bobsleigh                  Bronze      8
                           Gold        8
                           Silver      8
Cross Country Skiing       Bronze    113
                           Gold      113
                           Silver    113
Curling                    Bronze     25
                           Gold       25
                           Silver     25
Figure skating             Bronze     59
                           Gold       61
                           Silver     59
Freestyle Skiing           Bronze     17
                           Gold       17
                           Silver     17
Ice Hockey                 Bronze    102
                           Gold      101
                           Silver    102
Luge                       Bronze     15
                           Gold       15
                           Silver     15
Short Track Speed Skating  Bronze     48
                           Gold       48
                           Silver     47
Skeleton                   Bronze      4
                           Gold        4
                           Silver      4
Ski Jumping                Bronze      1
                           Gold        1
                           Silver      1
Snowboard                  Bronze     15
                           Gold       15
                           Silver     15
Speed skating              Bronze     78
                           Gold       81
                           Silver     83
dtype: int64

In [ ]:
winter_female_olympians.groupby(['Discipline', 'Medal']).size().head(30)

Discipline                 Medal
Alpine Skiing              Bronze     69
                           Gold       72
                           Silver     72
Biathlon                   Bronze     50
                           Gold       50
                           Silver     50
Bobsleigh                  Bronze      8
                           Gold        8
                           Silver      8
Cross Country Skiing       Bronze    113
                           Gold      113
                           Silver    113
Curling                    Bronze     25
                           Gold       25
                           Silver     25
Figure skating             Bronze     59
                           Gold       61
                           Silver     59
Freestyle Skiing           Bronze     17
                           Gold       17
                           Silver     17
Ice Hockey                 Bronze    102
                           Gold      101
                           Silver    102
Luge                       Bronze     15
                           Gold       15
                           Silver     15
Short Track Speed Skating  Bronze     48
                           Gold       48
                           Silver     47
dtype: int64

In [ ]:
winter_male_olympians.sort_values(by='Year', ascending=False).head(15)

#This will help us see how many male atheletes there are in each discipline for the winter olympics
winter_male_olympians.groupby('Discipline').size()

#nthis will help us see  which ones have medals won 
winter_male_olympians.groupby('Medal').size()

#this will now let us combine the two above so the number of female metals per each disicipline for the winter olympics
winter_male_olympians.groupby(['Discipline', 'Medal']).size()

Discipline                 Medal
Alpine Skiing              Bronze     72
                           Gold       71
                           Silver     72
Biathlon                   Bronze     89
                           Gold       90
                           Silver     91
Bobsleigh                  Bronze    139
                           Gold      126
                           Silver    133
Cross Country Skiing       Bronze    150
                           Gold      151
                           Silver    149
Curling                    Bronze     31
                           Gold       33
                           Silver     33
Figure skating             Bronze     59
                           Gold       61
                           Silver     60
Freestyle Skiing           Bronze     17
                           Gold       17
                           Silver     17
Ice Hockey                 Bronze    410
                           Gold      409
                           Silver    412
Luge                       Bronze     45
                           Gold       47
                           Silver     43
Nordic Combined            Bronze     55
                           Gold       55
                           Silver     55
Short Track Speed Skating  Bronze     48
                           Gold       49
                           Silver     50
Skeleton                   Bronze      6
                           Gold        6
                           Silver      6
Ski Jumping                Bronze     67
                           Gold       68
                           Silver     69
Snowboard                  Bronze     15
                           Gold       15
                           Silver     15
Speed skating              Bronze    112
                           Gold      112
                           Silver    114
dtype: int64

In [ ]:
winter_male_olympians.groupby(['Discipline', 'Medal']).size().head(30)

Discipline            Medal
Alpine Skiing         Bronze     72
                      Gold       71
                      Silver     72
Biathlon              Bronze     89
                      Gold       90
                      Silver     91
Bobsleigh             Bronze    139
                      Gold      126
                      Silver    133
Cross Country Skiing  Bronze    150
                      Gold      151
                      Silver    149
Curling               Bronze     31
                      Gold       33
                      Silver     33
Figure skating        Bronze     59
                      Gold       61
                      Silver     60
Freestyle Skiing      Bronze     17
                      Gold       17
                      Silver     17
Ice Hockey            Bronze    410
                      Gold      409
                      Silver    412
Luge                  Bronze     45
                      Gold       47
                      Silver     43
Nordic Combined       Bronze     55
                      Gold       55
                      Silver     55
dtype: int64

### Logistic Regression for Medal Type and Gender